export const seedItems = [
  {
    id: "oat",
    name: "오트밀크",
    category: "음료",
    unit: "1L",
    stock: 2,
    minimum: 5,
    target: 10,
  },
  {
    id: "vanilla",
    name: "바닐라 시럽",
    category: "시럽",
    unit: "1병",
    stock: 1,
    minimum: 4,
    target: 6,
  },
  {
    id: "cups",
    name: "테이크아웃 컵",
    category: "소모품",
    unit: "50ea",
    stock: 36,
    minimum: 100,
    target: 100,
  },
  {
    id: "beans",
    name: "하우스 블렌드 원두",
    category: "커피",
    unit: "1kg",
    stock: 3,
    minimum: 5,
    target: 15,
  },
  {
    id: "milk",
    name: "우유",
    category: "음료",
    unit: "1L",
    stock: 8,
    minimum: 5,
    target: 10,
  },
  {
    id: "cream",
    name: "휘핑크림",
    category: "음료",
    unit: "1L",
    stock: 4,
    minimum: 5,
    target: 10,
  },
  {
    id: "caramel",
    name: "카라멜 소스",
    category: "시럽",
    unit: "1병",
    stock: 6,
    minimum: 3,
    target: 6,
  },
  {
    id: "matcha",
    name: "말차 파우더",
    category: "파우더",
    unit: "500g",
    stock: 5,
    minimum: 2,
    target: 5,
  },
  {
    id: "lids",
    name: "테이크아웃 컵 리드",
    category: "소모품",
    unit: "50ea",
    stock: 120,
    minimum: 100,
    target: 150,
  },
  {
    id: "chocolate",
    name: "초콜릿 파우더",
    category: "파우더",
    unit: "1kg",
    stock: 3,
    minimum: 2,
    target: 5,
  },
];

export const initialState = () => ({
  items: seedItems.map((item) => ({ ...item })),
  queue: [],
  history: [],
});
